### PR TITLE
(feat) create post api integration

### PR DESCRIPTION
**Pull request by roncoderpush**
## What
- Complete create post flow, including adding event or upload image into post.

## How
- Add integration with event listing page to select event while create post
- Add image picker to allow user pick image while create post
- Fix the issue when user both select event and image, only the last selection will be applied.
- Fix the issue when uploading image fallback to status code 400 because file's content-type is incorrect.

## Screenshot
Simulator Screenshot - iPhone 14 Pro Max - 2023-08-15 at 10 50 50

Simulator Screenshot - iPhone 14 Pro Max - 2023-08-15 at 11 05 10

Simulator Screenshot - iPhone 14 Pro Max - 2023-08-15 at 11 05 50

### CODE REVIEW

**Review by sieuhuflit — CHANGES_REQUESTED** [review]
Some notes about UI improvement

260624802-b5b179fb-a172-4fa9-a85f-0970c732ac9b

---

260624720-d2fe4dd6-c32c-469b-b2ce-354aafaeac12

**Comment by roncoderpush** [comment]
@sieuhuflit @mthinh I have added some UI change, please take a look

Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 16 35 37

Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 16 43 37

**Comment by mthinh** [comment]
260969179-ea083a18-2013-4ad2-a4ed-5e18aef4ae18
Minor UI issue, please help check @roncoderpush

**Review by mthinh — CHANGES_REQUESTED** [review]
Please help check

**Review by sieuhuflit — APPROVED** [review]
LGTM 💯

**Pull request merged**
